name: Update NTAS Image

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pillow

      - name: Fetch and update NTAS image
        run: |
          python update_ntas_image.py
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add ntas_current_status.png
          git commit -m "Update NTAS image"
          git push
